version: '3.3'


services:
    postgres-learning_sql:
        image: postgres
        hostname: postgres
        container_name: postgres_db
        environment:
            POSTGRES_DB: 'lab'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - /var/postgres/db_data1:/var/lib/postgresql/data
        ports:
           - "5432:5432"



